# Generated by Django 5.0.7 on 2024-08-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sec', '0002_funcionario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrasFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade_treinamento', models.DateField()),
                ('advertencia_obs', models.TextField()),
                ('advertencia_anexo', models.FileField(upload_to='profile_advertencia/%Y/%m/%d/')),
                ('atestado_obs', models.TextField()),
                ('atestado_anexo', models.FileField(upload_to='profile_atestado/%Y/%m/%d/')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_sec.funcionario')),
            ],
        ),
    ]
