# Generated by Django 5.0.7 on 2024-08-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sec', '0004_funcionario_admissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
