# Generated by Django 5.0.7 on 2024-08-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sec', '0005_funcionario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
